### ISSUE TITLE
[FOTA] 基本構造設計(アーキテクチャ図、レビュー)

### ISSUE THREAD

**Issue by Kunio-AL** [aeterlink-dev/Edge_SW_Task#17]

**Comment by hKato-AL** [comment]
### **AP1.5 向けOTA更新システム概要設計**

#### 1. 概要
* **SWUpdate Single Copy機能**を使い、Pythonアプリを含む複数サービスを安全にOTA更新
* **外部サーバーをポーリング**し、設定ファイルから新バージョン／ダウンロードURL／認証トークンを取得
* **パッケージダウンロード→バックアップ→更新適用→バージョン書き換え→クリーンアップ**のでエラー検知
* エラー検知時は**バックアップから自動リストア**し、それでも失敗した場合は**外部通知**（Webhookなど）

---

#### 2. 現在の課題

* バージョン差異だけを記載していますが、個別対応について行うか？
* 更新失敗などを何処で受けるか、対応についてどうするか？

---

#### 3. 関与システム略図

![Image](https://github.com/user-attachments/assets/3a309459-4b07-40c9-8dbd-6d493deb5c5f)

---

#### 4.  機能要件（簡略）

* **定期確認：** cron で `/ota/check_update.sh` をポーリング動作（個別対応？→課題）
* **バージョン比較：** リモート JSON と `version.txt` を照合し確認
* **安全なダウンロード：** GitHub から `Authorization: token` 付きでダウンロード取得
* **バックアップ：** 本番では簡易的、 `delete_list.txt` と `install_list.txt` と `ota` を書き戻し対応
* **プレポスト処理実行：** 共通/サービス別のプレ・ポスト削除処理対応
* **更新ファイル展開：** 本版では簡易的、ルート直下に直接展開
* **状態更新：** `version.txt` 書換、一時領域を全削除
* **復元処理：** アップデート失敗時にバックアップから対象ファイルのみ復元（pip環境など対象外）
* **通知：** 更新失敗結果を Webhookで通知（何処に置くか？→課題）

---

#### 5. 更新フロー概略

```
1. cron → /ota/check_update.sh 実行
2. GitHub から JSON 取得 → version 比較（同一なら終了）
3. 認証付きでパッケージ DL（GitHub Releases）
4. delete_list.txt に基づく削除対象ファイルバックアップ
   ＆ install_list.txt に基づく個別ファイルバックアップ
   ＆ OTA ロジック丸ごとバックアップ
5. pre_delete フック実行 ＆ 各サービス pre フック実行
6. Single-Copy 展開（ルート直下へ一発展開）
7. post_install フック実行 ＆ 各サービス post フック実行
8. version.txt 書換 ＆ /tmp/ota クリーンアップ
9. 正常終了 / 失敗時は削除対象ファイル復元
   ＆ 個別ファイル復元 ＆ OTA ロジック復元 ＆ 通知
```

---

#### 6. ディレクトリ構成と設定ファイル

```
/ota/
 ├─ version.txt
 ├─ check_update.sh
 ├─ config/
 │   ├─ delete_list.txt    # 削除対象ファイルリスト
 │   └─ install_list.txt   # インストール対象ファイルリスト
 ├─ hooks/
 │   ├─ pre_delete.sh      # 共通プレ処理（削除）
 │   ├─ post_install.sh    # 共通ポスト処理
 │   └─ <service>/
 │        ├─ pre.sh        # サービス固有プレ処理
 │        └─ post.sh       # サービス固有ポスト処理
 └─ log/

/tmp/ota/
 ├─ ota_config.json
 └─ update_package.tar.gz

/opt/app/

/ota/backup/
 ├─ app/   (.tar.gz)
 └─ ota/   (.tar.gz)
```

---

#### 7. 失敗時リストア

* `trap 'on_error' ERR` によるエラー検知
* `install_list.txt` の各ファイルを `/ota/backup/app/` から復元
* `/ota` 配下を `/ota/backup/ota/` から復元
* 通知用 Webhook

---

#### 8. SWUpdate マニフェスト

```ini
software =
{
    version    = "${VERSION}";
    singlecopy = true;
    description= "AP1.5 OTA Update";

    files: (
        { filename = "opt/app/"; path = "/opt/app/"; type = "dir"; },
        { filename = "ota/";     path = "/ota/";     type = "dir"; },
    );
}
```

#### 9. フックスクリプト例

* /ota/hooks/pre_delete.sh

  ```bash
  while IFS= read -r file; do [ -e "$file" ] && rm -rf "$file"; done < /ota/config/delete_list.txt
  ```

* /ota/hooks/<service>/pre.sh

  ```bash
  # 例: serviceX の古いファイル削除
  rm -f /opt/app/bin/serviceX_old
  ```

* /ota/hooks/post_install.sh

  ```bash
  [ -f /opt/app/lib/requirements.txt ] && pip install -r /opt/app/lib/requirements.txt
  ```

* /ota/hooks/<service>/post.sh

  ```bash
  /opt/app/bin/serviceY migrate
  ```

#### 10. 設定 JSON サンプル

```json
{
  "version": "1.2.3",
  "update_url": "https://github.com/owner/repo/releases/download/v1.2.3/update_package.tar.gz",
  "pat": "<GitHubトークン>",
  "services": ["serviceX","serviceY"]
}
```

**Comment by hKato-AL** [comment]
A/Bバンク方式についての追加検討（ @gkuga ）

* bm-air_control
    * main.py : [THIS_DIR_PATH = os.path.join(os.path.dirname(__file__))](https://github.com/aeterlink-dev/bm-air_control/blob/da25d683efb9998c585bd1faeb0c951687e8b650/main.py#L17)    # 取得のみ以後未使用
    * httprest_handler.py : [bodydata, fpath = None, ""](https://github.com/aeterlink-dev/bm-air_control/blob/64ca7d1b703b3c1d9e4bfde947f080185582c610/httprest_handler.py#L150)    # 空だし利用してない
    * control.py : [params.write_csv('./config/params.csv')](https://github.com/aeterlink-dev/bm-air_control/blob/681df1808f8f2dccafc86f607ccc2473d6ca8c97/control.py#L94)    # 自path配下参照
    * control.py : [params = pl.read_csv('./config/params.csv')](https://github.com/aeterlink-dev/bm-air_control/blob/681df1808f8f2dccafc86f607ccc2473d6ca8c97/control.py#L101)    #  自path配下参照
    * control.py : [direc = glob.glob('./data/prev_ctl.csv')](https://github.com/aeterlink-dev/bm-air_control/blob/681df1808f8f2dccafc86f607ccc2473d6ca8c97/control.py#L134)    #  自path配下参照
    * control.py : [direc.write_csv('./data/prev_ctl.csv')](https://github.com/aeterlink-dev/bm-air_control/blob/681df1808f8f2dccafc86f607ccc2473d6ca8c97/control.py#L142)   #  自path配下参照
    * control.py : [direc = pl.read_csv('./data/prev_ctl.csv')](https://github.com/aeterlink-dev/bm-air_control/blob/681df1808f8f2dccafc86f607ccc2473d6ca8c97/control.py#L144)   #  自path配下参照
    * control.py : [df.write_csv('./data/data_frame.csv')](https://github.com/aeterlink-dev/bm-air_control/blob/681df1808f8f2dccafc86f607ccc2473d6ca8c97/control.py#L214)
    * control.py : [direc.write_csv('./data/prev_ctl.csv')](https://github.com/aeterlink-dev/bm-air_control/blob/681df1808f8f2dccafc86f607ccc2473d6ca8c97/control.py#L215)

**Comment by hKato-AL** [comment]
DEVICE個体確認について

* 個体識別で利用できるタグについて
    1. config.yml // token **この辺りを使いCloudAPI認証でID拾う方向で**
    2. prometeuth // sumit-id
    3. eth0 // macaddress
    
* GitHubリリースの構成 / リリース個体の識別方法 の明文化
    * 記載の追加

* 成功失敗の記録
    * CloudAPIに対し、失敗/成功を返すAPIを用意予定たぶんそのうち

**Comment by hKato-AL** [comment]
# AP1.5 向け FOTA 更新システム概要設計

---

## 1. 概要

- **目的**
  - AP1.5 Sumit 向けに、アプリケーション実行コードおよび個別コンフィグを自動かつ効率的に更新（FOTA）する仕組みを構築
- **対象規模**
  - 数百台想定（数千台以上であれば CDN や専用配信サーバ導入を検討）
- **管理リポジトリ**
  - `app-repo`: アプリ実行コード（GitHub Releases）
  - `conf-repo`: コンフィグ（monorepo 化された YAML）

## 2. 改善すべき現状の課題
- Sumit ごとに個別コンフィグを手動管理しており、バージョン同期が煩雑
- 設定変更手順が散在し、運用フローが未整備
- 手動運用によるミスや遅延リスクが高い
- config 更新時の不要コード再取得によるリソース無駄遣い

## 3. 関与システム概要図

```
+------------------------+           +-------------------------+
|        GitHub         |           |    GitHub Releases     |
| • app-repo (Releases) |           | (bundle アセット格納)   |
| • conf-repo           |           +-----------+-------------+
+-----------+-----------+                       |
            | push/tag                            | download
            v                                     v
+-------------------------+         +------------------------+
| GitHub Actions (CI)    |         | AP1.5 Sumit           |
| • deploy.yml           |--publish->| • OTA エージェント    |
+-------------------------+         +------------------------+
```
- CI が生成した bundle は GitHub Releases のアセットとして格納され、Sumit はそこから直接ダウンロードします。

## 4. バージョン構成
- `app_version` はアプリケーションバージョンで、リリース用の app-repo で更新
- `conf_version` はコンフィギュレーションバージョンで、Sumit-id + version で構成し、conf-repo で更新
- `conf-repo` の各 Sumit 用 `config.yaml` 内で `app_version` を管理
  - Sumit のコンフィグバージョンがアプリ実行コードのバージョンを内在する形で参照する構成

## 5. リポジトリ構成（path tree）

```
app-repo/
├ .github/
│  └ workflows/
│     └ release.yml       # 実行コード生成＆Publish
├ src/                   # アプリソース（Python スクリプト含む）
└ build/                 # CI ビルド成果物

conf-repo/
├ .github/
│  └ workflows/
│     └ deploy.yml       # config更新→Bundle生成＆Publish
├ configs/
│  ├ sumit-001/config.yaml   # Appバージョン, Pre/Post.shを内包
│  ├ sumit-002/config.yaml   # Appバージョン, Pre/Post.shを内包
│  └ ...
├ release-manifest.yaml # バージョン宣言マニフェスト
└ scripts/
   └ deploy_to_sumit.sh # Bundle展開スクリプト
```

## 6. 機能要件

| No  | 要件内容                                                      |
|-----|--------------------------------------------------------------|
| R1  | `app-repo` にてタグ（vX.Y.Z）＋GitHub Releasesで管理        |
| R2  | `conf-repo` の `app_version` 更新のみでコード自動取得→FOTA |
| R3  | config 変更／タグプッシュ時に GitHub Actions で CI 実行    |
| R4  | バージョン差異検知により不要ダウンロードをスキップ        |
| R5  | 数千台規模時は CDN ミラーリングや配信サーバ追加を検討      |

## 7. 更新フロー（概要）

1. `conf-repo` で **`app_version` のみ** を更新（`configs/sumit-XXX/config.yaml`）
2. PR → マージ → `push` イベント発生
3. GitHub Actions (`deploy.yml`) が差分検知 → `app_version` を抽出
4. 直前版と比較し、差分ありの場合のみ GitHub Releases から実行コードをダウンロード
5. ローカルに `bundle/` フォルダを作成し、以下を配置:
   - ダウンロードした実行コード
   - 対象 `config.yaml`
6. CI で生成した `bundle_sumit-XXX_vX.Y.Z.tar.gz` はリポジトリに含めず、該当リリースのアセットとしてアップロード
7. Sumit が定期的または起動時に GitHub Releases から最新 bundle をダウンロード → 展開 → 再起動

## 8. 想定構成サービス

- **GitHub**
  - `app-repo`: 実行コード配信 (Releases)
  - `conf-repo`: コンフィグ管理 (monorepo)
- **CI/CD**: GitHub Actions
- **配信プラットフォーム**: GitHub Releases (小〜中規模向け)
- **OTA エージェント**: Sumit 側で FOTA 処理を実装

## 9. マニフェスト例

```yaml
# release-manifest.yaml
app_repo: your-org/app-repo
app_version: v1.2.3
```

## 10. Publish スクリプトサンプル

```yaml
# configs/sumit-002/config.yaml
app_version: v1.2.3
pre_commands: |
  systemctl stop sumit.service
  mv /opt/sumit/app /opt/sumit/app.bak
post_commands: |
  mv /opt/sumit/app.bak/app /opt/sumit/app
  systemctl start sumit.service
```


## 11. GitHub Actions サンプル

### app-repo/.github/workflows/release.yml

```yaml
name: Build & Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make build  # Python スクリプトパッケージやバイナリ生成
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: "./build/*"
```

### conf-repo/.github/workflows/deploy.yml

```yaml
name: Deploy on Config Change
on:
  push:
    paths:
      - 'configs/**/config.yaml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Detect changed config
        id: find
        run: |
          echo "::set-output name=path::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }}             | grep 'configs/.*/config.yaml')"
      - name: Extract versions
        id: versions
        run: |
          PREV=$(git show ${{ github.event.before }}:${{ steps.find.outputs.path }} | yq e '.app_version' -)
          CUR=$(yq e '.app_version' ${{ steps.find.outputs.path }})
          echo "::set-output name=prev::$PREV"
          echo "::set-output name=curr::$CUR"
      - name: Download code if changed
        if: steps.versions.outputs.prev != steps.versions.outputs.curr
        run: |
          gh release download ${{ steps.versions.outputs.curr }} --repo your-org/app-repo --pattern '*.tar.gz'
      - name: Package and Publish
        run: |
          mkdir bundle && tar zxvf *.tar.gz -C bundle
          cp ${{ steps.find.outputs.path }} bundle/
          gh release upload ${{ steps.versions.outputs.curr }} bundle/*
```
