### ISSUE TITLE
[incident] ソフトバンク竹芝　BT ペアリング問題（データ取得できない）

### ISSUE THREAD

**Issue by Kunio-AL** [aeterlink-dev/Edge_SW_Task#18]

**Comment by SueHiro199** [comment]
bluetoothctlコマンドでペアリングされていないPTxを確認
（pairコマンドを試したがFailedに）
×：ペアリングされていないPTx

hci1 08:BE:AC:41:D6:35
 T09ABA-10000E400045 ×
 T09ABA-10000E400044
 T09ABA-10000E400041
 T09ABA-10000E400040
 T09ABA-10000E400039

hci2 08:BE:AC:41:D6:31
 T09ABA-10000E400043 ×
 T09ABA-10000E400042 ×
 T09ABA-10000E400038 ×
 T09ABA-10000E400037 ×

hci3 08:BE:AC:41:D4:9B
 T09ABA-10000E400052
 T09ABA-10000E400051
 T09ABA-10000E400049
 T09ABA-10000E400048

hci4 08:BE:AC:41:D6:2C
 T09ABA-10000E400054 ×
 T09ABA-10000E400053 ×
 T09ABA-10000E400050 ×
 T09ABA-10000E400047 ×
 T09ABA-10000E400046 ×


```
select 08:BE:AC:41:D6:35
Controller 08:BE:AC:41:D6:35 atde9 #2 [default]
[bluetooth]# paired-devices
Device 94:B2:16:31:50:0D T09ABA-10000E400044
Device 94:B2:16:31:4C:DB T09ABA-10000E400040
Device 94:B2:16:31:50:6D T09ABA-10000E400039
Device 94:B2:16:31:4E:EB T09ABA-10000E400041

select 08:BE:AC:41:D6:31
Controller 08:BE:AC:41:D6:31 atde9 #3 [default]
[bluetooth]# paired-devices

select 08:BE:AC:41:D4:9B
Controller 08:BE:AC:41:D4:9B atde9 #4 [default]
[bluetooth]# paired-devices
Device 94:B2:16:31:4E:E7 T09ABA-10000E400048
Device 94:B2:16:31:50:71 T09ABA-10000E400052
Device 94:B2:16:31:4F:D7 T09ABA-10000E400051
Device 94:B2:16:31:50:12 T09ABA-10000E400049

select 08:BE:AC:41:D6:2C
Controller 08:BE:AC:41:D6:2C atde9 [default]
[bluetooth]# paired-devices

```

**Comment by SueHiro199** [comment]
/etc/sumit/config.yaml の static_adapters: の並びが hciconfig コマンド出力内容の hci番号順序と異なっていたため、同じ並びとなるよう修正
（Sumit・関連機器のリブートや電源断でhciの順序が変わることがある事象は既知事象（[Type Dペアリング手順](https://docs.google.com/document/d/1S_bmB28i71C0QrnkOjufzvxt1DGvvEBYAO5F-lDkmFY/edit?tab=t.6il3ycpv4k8b)）とのこと）

```
:
static_adapters:
  - public_address: "08:BE:AC:41:D6:35"
  - public_address: "08:BE:AC:41:D6:31"
  - public_address: "08:BE:AC:41:D4:9B"
  - public_address: "08:BE:AC:41:D6:2C"
:
```

hciconfig コマンド出力内容
```
hci4:   Type: Primary  Bus: USB
        BD Address: 08:BE:AC:41:D6:2C  ACL MTU: 1021:6  SCO MTU: 255:12
        UP RUNNING
        RX bytes:32907162 acl:0 sco:0 events:220225 errors:0
        TX bytes:998326 acl:0 sco:0 commands:53268 errors:0

hci3:   Type: Primary  Bus: USB
        BD Address: 08:BE:AC:41:D4:9B  ACL MTU: 1021:6  SCO MTU: 255:12
        UP RUNNING
        RX bytes:32773477 acl:65482 sco:0 events:204564 errors:0
        TX bytes:1123285 acl:24485 sco:0 commands:33352 errors:0

hci2:   Type: Primary  Bus: USB
        BD Address: 08:BE:AC:41:D6:31  ACL MTU: 1021:6  SCO MTU: 255:12
        UP RUNNING
        RX bytes:22260579 acl:0 sco:0 events:190484 errors:0
        TX bytes:1116483 acl:0 sco:0 commands:62957 errors:0

hci1:   Type: Primary  Bus: USB
        BD Address: 08:BE:AC:41:D6:35  ACL MTU: 1021:6  SCO MTU: 255:12
        UP RUNNING
        RX bytes:30471307 acl:70430 sco:0 events:197850 errors:0
        TX bytes:1087093 acl:21798 sco:0 commands:33617 errors:0

hci0:   Type: Primary  Bus: UART
        BD Address: 2C:3B:70:C4:D3:5A  ACL MTU: 1021:7  SCO MTU: 120:6
        UP RUNNING
        RX bytes:181469 acl:0 sco:0 events:12167 errors:0
        TX bytes:514969 acl:0 sco:0 commands:12167 errors:0
```

**Comment by SueHiro199** [comment]
（参考）

![Image](https://github.com/user-attachments/assets/0924dbe8-d25a-4e98-9ebd-a6011ce864f6)

**Comment by SueHiro199** [comment]
/etc/sumit/config.yaml の ports: に相当するCloud登録内容についても順序を修正する必要がある

```
ports:
  - name: auto
    nodes:
      - uid: "T09ABA-10000E400045"
        slave_id: 9
        power_supply_on: true
        led_control_on: true
      - uid: "T09ABA-10000E400044"
        slave_id: 8
        power_supply_on: true
        led_control_on: true
      - uid: "T09ABA-10000E400041"
        slave_id: 5
        power_supply_on: true
        led_control_on: true
      - uid: "T09ABA-10000E400040"
        slave_id: 4
        power_supply_on: true
        led_control_on: true
      - uid: "T09ABA-10000E400039"
        slave_id: 3
        power_supply_on: true
        led_control_on: true
  - name: auto
    nodes:
      - uid: "T09ABA-10000E400054"
        slave_id: 18
        power_supply_on: true
        led_control_on: true
      - uid: "T09ABA-10000E400053"
        slave_id: 17
        power_supply_on: true
        led_control_on: true
      - uid: "T09ABA-10000E400050"
        slave_id: 14
        power_supply_on: true
        led_control_on: true
      - uid: "T09ABA-10000E400047"
        slave_id: 11
        power_supply_on: true
        led_control_on: true
      - uid: "T09ABA-10000E400046"
        slave_id: 10
        power_supply_on: true
        led_control_on: true
  - name: auto
    nodes:
      - uid: "T09ABA-10000E400052"
        slave_id: 16
        power_supply_on: true
        led_control_on: true
      - uid: "T09ABA-10000E400051"
        slave_id: 15
        power_supply_on: true
        led_control_on: true
      - uid: "T09ABA-10000E400049"
        slave_id: 13
        power_supply_on: true
        led_control_on: true
      - uid: "T09ABA-10000E400048"
        slave_id: 12
        power_supply_on: true
        led_control_on: true
  - name: auto
    nodes:
      - uid: "T09ABA-10000E400043"
        slave_id: 7
        power_supply_on: true
        led_control_on: true
      - uid: "T09ABA-10000E400042"
        slave_id: 6
        power_supply_on: true
        led_control_on: true
      - uid: "T09ABA-10000E400038"
        slave_id: 2
        power_supply_on: true
        led_control_on: true
      - uid: "T09ABA-10000E400037"
        slave_id: 1
        power_supply_on: true
        led_control_on: true
```


![Image](https://github.com/user-attachments/assets/3a2db8fb-6de3-43a2-bb4d-b8576c746edd)
